In [1]:
import pandas as pd

transactions=pd.read_csv("bronze/bronze_raw_transactions.csv")
transactions

,transaction_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,payment_method,order_status,sales_channel,source_system,last_modified
0,1,2025-02-03,4593.0,853,2.0,15213.86,0.00,Debit Card,Returned,Website,Ecommerce,2025-02-05 05:00:00
1,2,2025-05-15,21441.0,844,2.0,34802.76,0.00,Credit Card,Completed,Mobile App,ERP,2025-05-16 18:00:00
2,3,2025-04-10,32078.0,560,4.0,16944.67,0.00,Cash,Cancelled,Website,ERP,2025-04-12 20:00:00
3,4,2025-06-27,16862.0,985,5.0,17010.34,0.10,Debit Card,Completed,Store,ERP,2025-06-27 08:00:00
4,5,2025-01-14,16297.0,532,5.0,37642.03,0.15,Net Banking,Cancelled,Store,POS,2025-01-15 09:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1002495,771300,2025-09-25,39285.0,940,1.0,32213.16,0.00,Cash,Completed,Mobile App,Ecommerce,2025-09-25 22:00:00
1002496,776223,2025-11-13,12264.0,946,6.0,6413.69,0.00,UPI,Returned,Mobile App,ERP,2025-11-14 12:00:00
1002497,343101,2025-12-24,28381.0,531,2.0,39173.17,0.00,Cash,Completed,Mobile App,Ecommerce,2025-12-26 22:00:00
1002498,639415,2025-01-07,21940.0,30,1.0,43693.59,0.20,Cash,Pending,Website,Ecommerce,2025-01-07 22:00:00
1002499,450716,2025-07-21,29196.0,1000,7.0,11738.38,0.00,Debit Card,Completed,Store,ERP,2025-07-22 23:00:00

In [2]:
#1. Load the transactions CSV and display the first 10 rows.

transactions.head(10)

,transaction_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,payment_method,order_status,sales_channel,source_system,last_modified
0,1,2025-02-03,4593.0,853,2.0,15213.86,0.00,Debit Card,Returned,Website,Ecommerce,2025-02-05 05:00:00
1,2,2025-05-15,21441.0,844,2.0,34802.76,0.00,Credit Card,Completed,Mobile App,ERP,2025-05-16 18:00:00
2,3,2025-04-10,32078.0,560,4.0,16944.67,0.00,Cash,Cancelled,Website,ERP,2025-04-12 20:00:00
3,4,2025-06-27,16862.0,985,5.0,17010.34,0.10,Debit Card,Completed,Store,ERP,2025-06-27 08:00:00
4,5,2025-01-14,16297.0,532,5.0,37642.03,0.15,Net Banking,Cancelled,Store,POS,2025-01-15 09:00:00
5,6,2025-12-08,4483.0,498,6.0,37225.77,0.00,UPI,Completed,Store,POS,2025-12-10 22:00:00
6,7,2025-06-22,28295.0,356,7.0,1560.11,0.00,Credit Card,Pending,Mobile App,Ecommerce,2025-06-22 22:00:00
7,8,2025-05-10,10376.0,193,3.0,15442.65,0.00,Debit Card,Completed,Website,Ecommerce,2025-05-11 15:00:00
8,9,2025-11-18,2205.0,804,7.0,47438.91,0.00,UPI,Completed,Mobile App,Ecommerce,2025-11-18 01:00:00
9,10,2025-07-29,44315.0,523,3.0,13081.92,0.20,Net Banking,Completed,Website,POS,2025-07-29 06:00:00

In [3]:
# 2. Print row count, column count, column names, and data types.
transactions.shape

(1002500, 12)

In [4]:
transactions.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'unit_price', 'discount_pct', 'payment_method', 'order_status',
       'sales_channel', 'source_system', 'last_modified'],
      dtype='str')

In [5]:
transactions.dtypes

transaction_id      int64
order_date            str
customer_id       float64
product_id          int64
quantity          float64
unit_price        float64
discount_pct      float64
payment_method        str
order_status          str
sales_channel         str
source_system         str
last_modified         str
dtype: object

In [6]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1002500 entries, 0 to 1002499
Data columns (total 12 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   transaction_id  1002500 non-null  int64
 1   order_date      1002500 non-null  str
 2   customer_id     1001497 non-null  float64
 3   product_id      1002500 non-null  int64
 4   quantity        1000994 non-null  float64
 5   unit_price      1002500 non-null  float64
 6   discount_pct    1002500 non-null  float64
 7   payment_method  1001496 non-null  str
 8   order_status    1002500 non-null  str
 9   sales_channel   1002500 non-null  str
 10  source_system   1002500 non-null  str
 11  last_modified   1002500 non-null  str
dtypes: float64(4), int64(2), str(6)
memory usage: 91.8 MB

In [7]:
# 4. Find duplicate rows and duplicate `transaction_id` values.
transactions_cleaned=transactions.drop_duplicates(subset=["transaction_id"],keep='first')
transactions_cleaned

,transaction_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,payment_method,order_status,sales_channel,source_system,last_modified
0,1,2025-02-03,4593.0,853,2.0,15213.86,0.00,Debit Card,Returned,Website,Ecommerce,2025-02-05 05:00:00
1,2,2025-05-15,21441.0,844,2.0,34802.76,0.00,Credit Card,Completed,Mobile App,ERP,2025-05-16 18:00:00
2,3,2025-04-10,32078.0,560,4.0,16944.67,0.00,Cash,Cancelled,Website,ERP,2025-04-12 20:00:00
3,4,2025-06-27,16862.0,985,5.0,17010.34,0.10,Debit Card,Completed,Store,ERP,2025-06-27 08:00:00
4,5,2025-01-14,16297.0,532,5.0,37642.03,0.15,Net Banking,Cancelled,Store,POS,2025-01-15 09:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,2025-08-29,35587.0,493,1.0,43648.31,0.00,Cash,Cancelled,Store,ERP,2025-08-31 04:00:00
999996,999997,2025-02-11,37772.0,141,2.0,41632.12,0.05,Debit Card,Completed,Store,POS,2025-02-13 16:00:00
999997,999998,2025-09-12,32544.0,891,6.0,7390.87,0.15,Net Banking,Returned,Mobile App,ERP,2025-09-13 07:00:00
999998,999999,2025-07-01,18873.0,874,1.0,32474.39,0.00,Credit Card,Completed,Store,ERP,2025-07-01 11:00:00
999999,1000000,2025-09-26,48937.0,85,3.0,44612.19,0.10,Debit Card,Completed,Store,Ecommerce,2025-09-28 06:00:00

In [8]:
# 5. Show the top 10 most frequent order statuses.
transactions_cleaned['order_date']=pd.to_datetime(transactions_cleaned['order_date'])
frequent_10_orders=transactions_cleaned.sort_values(['order_date'],ascending=[False]).head(10)
frequent_10_orders['order_status']

767962    Completed
280366      Pending
430879      Pending
837596     Returned
617531    Completed
308320    Completed
308234      Pending
431201     Returned
836834    Completed
517131    Completed
Name: order_status, dtype: str

In [9]:
# 6. Find minimum and maximum `order_date`.
transactions_cleaned['order_date'].min()

Timestamp('2025-01-01 00:00:00')

In [10]:
transactions_cleaned['order_date'].max()

Timestamp('2025-12-31 00:00:00')

In [11]:
transactions.dtypes

transaction_id      int64
order_date            str
customer_id       float64
product_id          int64
quantity          float64
unit_price        float64
discount_pct      float64
payment_method        str
order_status          str
sales_channel         str
source_system         str
last_modified         str
dtype: object

In [12]:
# 7. Identify columns that need type conversion and convert dates/numeric columns safely.
customers=pd.read_csv("bronze/customers.csv")
customers.dtypes

customer_id         int64
customer_name         str
email                 str
city                  str
state                 str
signup_date           str
customer_segment      str
dtype: object

In [13]:
customers['signup_date']=pd.to_datetime(customers['signup_date'])

In [14]:
products=pd.read_csv("bronze/products.csv")
products.dtypes

product_id        int64
product_name        str
category            str
unit_price      float64
supplier_id       int64
dtype: object

In [15]:
# Reading data in chunk
chunk_size=100000

for index,chunk in enumerate(pd.read_csv('bronze/bronze_raw_transactions.csv',chunksize=chunk_size)):
    print(f'CHUNK {index+1}')
    print(chunk)

CHUNK 1
       transaction_id  order_date  customer_id  product_id  quantity  \
0                   1  2025-02-03       4593.0         853       2.0
1                   2  2025-05-15      21441.0         844       2.0
2                   3  2025-04-10      32078.0         560       4.0
3                   4  2025-06-27      16862.0         985       5.0
4                   5  2025-01-14      16297.0         532       5.0
...               ...         ...          ...         ...       ...
99995           99996  2025-08-11       5800.0         771       6.0
99996           99997  2025-10-06      19346.0         931       4.0
99997           99998  2025-05-01       7178.0         343       2.0
99998           99999  2025-05-16      21516.0         796       4.0
99999          100000  2025-08-07        385.0         935       4.0

       unit_price  discount_pct payment_method order_status sales_channel  \
0        15213.86          0.00     Debit Card     Returned       Website
1        34802.76          0.00    Credit Card    Completed    Mobile App
2        16944.67          0.00           Cash    Cancelled       Website
3        17010.34          0.10     Debit Card    Completed         Store
4        37642.03          0.15    Net Banking    Cancelled         Store
...           ...           ...            ...          ...           ...
99995     3257.15          0.05            UPI    Completed         Store
99996    26081.61          0.10    Net Banking     Returned         Store
99997    33375.16          0.00           Cash    Completed    Mobile App
99998    36339.44          0.00    Net Banking    Cancelled         Store
99999    11368.18          0.15     Debit Card    Completed         Store

      source_system        last_modified
0         Ecommerce  2025-02-05 05:00:00
1               ERP  2025-05-16 18:00:00
2               ERP  2025-04-12 20:00:00
3               ERP  2025-06-27 08:00:00
4               POS  2025-01-15 09:00:00
...             ...                  ...
99995           POS  2025-08-12 13:00:00
99996           POS  2025-10-08 14:00:00
99997           POS  2025-05-03 14:00:00
99998           POS  2025-05-17 22:00:00
99999     Ecommerce  2025-08-08 22:00:00

[100000 rows x 12 columns]
CHUNK 2
        transaction_id  order_date  customer_id  product_id  quantity  \
100000          100001  2025-12-13      20996.0         661       4.0
100001          100002  2025-07-12      26026.0         224       5.0
100002          100003  2025-08-26       4816.0         981       2.0
100003          100004  2025-04-14      15054.0         485       5.0
100004          100005  2025-07-16      34854.0         725       7.0
...                ...         ...          ...         ...       ...
199995          199996  2025-08-26      30534.0         631       5.0
199996          199997  2025-08-06       2004.0         371       5.0
199997          199998  2025-11-16       9887.0         224       2.0
199998          199999  2025-01-09      45712.0         732       5.0
199999          200000  2025-08-12      48040.0         292       4.0

        unit_price  discount_pct payment_method order_status sales_channel  \
100000    38171.27          0.10           Cash    Cancelled       Website
100001    40136.70          0.00    Credit Card    Completed         Store
100002    30832.51          0.15    Net Banking      Pending    Mobile App
100003    25721.45          0.00           Cash      Pending    Mobile App
100004    25311.87          0.05            UPI    Completed       Website
...            ...           ...            ...          ...           ...
199995    43055.42          0.05            UPI    Cancelled    Mobile App
199996    26461.40          0.00     Debit Card      Pending       Website
199997    40136.70          0.00           Cash    Completed    Mobile App
199998     6762.93          0.00     Debit Card    Cancelled         Store
199999    15561.36          0.15            UPI    Completed    Mobile App

       source_system        last_modified
100000     Ecommerce  2025-12-13 02:00:00
100001     Ecommerce  2025-07-13 12:00:00
100002           POS  2025-08-26 06:00:00
100003           POS  2025-04-15 02:00:00
100004           POS  2025-07-17 18:00:00
...              ...                  ...
199995           ERP  2025-08-26 12:00:00
199996     Ecommerce  2025-08-07 20:00:00
199997           POS  2025-11-18 17:00:00
199998           POS  2025-01-09 01:00:00
199999           ERP  2025-08-12 10:00:00

[100000 rows x 12 columns]
CHUNK 3
        transaction_id  order_date  customer_id  product_id  quantity  \
200000          200001  2025-11-05      36641.0         135       6.0
200001          200002  2025-01-06      26650.0         742       6.0
200002          200003  2025-01-20      18278.0         909       2.0
200003          200004  2025-05-31        719.0         891       1.0
200004          200005  2025-11-25      20147.0         632       6.0
...                ...         ...          ...         ...       ...
299995          299996  2025-08-17      28757.0         883       3.0
299996          299997  2025-01-14      21641.0         901       1.0
299997          299998  2025-11-13      28788.0         397       4.0
299998          299999  2025-01-29      17172.0          22       7.0
299999          300000  2025-09-16      31905.0         620       5.0

        unit_price  discount_pct payment_method order_status sales_channel  \
200000     8262.30          0.15           Cash    Cancelled         Store
200001    17587.99          0.00            UPI    Completed         Store
200002    28087.76          0.05    Credit Card      Pending       Website
200003     7390.87          0.05    Net Banking    Cancelled         Store
200004     8372.01          0.00            UPI     Returned    Mobile App
...            ...           ...            ...          ...           ...
299995    27364.22          0.05           Cash    Completed       Website
299996    24407.73          0.05            UPI    Cancelled       Website
299997    19557.95          0.00    Net Banking      Pending         Store
299998    17610.91          0.10    Net Banking    Completed         Store
299999     5465.15          0.05    Net Banking    Completed       Website

       source_system        last_modified
200000     Ecommerce  2025-11-06 10:00:00
200001           POS  2025-01-07 06:00:00
200002     Ecommerce  2025-01-20 15:00:00
200003           POS  2025-06-02 15:00:00
200004     Ecommerce  2025-11-26 16:00:00
...              ...                  ...
299995           ERP  2025-08-17 14:00:00
299996           POS  2025-01-16 05:00:00
299997           POS  2025-11-15 09:00:00
299998           ERP  2025-01-29 00:00:00
299999           POS  2025-09-18 07:00:00

[100000 rows x 12 columns]
CHUNK 4
        transaction_id  order_date  customer_id  product_id  quantity  \
300000          300001  2025-12-15      14627.0         486       1.0
300001          300002  2025-05-15      44156.0         225       5.0
300002          300003  2025-11-22      38413.0         198       6.0
300003          300004  2025-12-03      10914.0         384       3.0
300004          300005  2025-02-23      37179.0         635       2.0
...                ...         ...          ...         ...       ...
399995          399996  2025-04-11      41048.0         933       5.0
399996          399997  2025-04-07      35029.0         629       7.0
399997          399998  2025-12-11       7509.0         915       5.0
399998          399999  2025-12-15        328.0         939       6.0
399999          400000  2025-12-05      23564.0         455       6.0

        unit_price  discount_pct payment_method order_status sales_channel  \
300000    18986.50          0.05    Net Banking    Completed       Website
300001    47748.58          0.10     Debit Card     Returned       Website
300002    16575.72          0.00           Cash    Completed       Website
300003     8798.58          0.05    Net Banking    Cancelled         Store
300004      756.07          0.05           Cash      Pending    Mobile App
...            ...           ...            ...          ...           ...
399995    38318.59          0.10    Credit Card    Cancelled         Store
399996    13917.49          0.05    Net Banking     Returned         Store
399997    36407.48          0.00    Net Banking      Pending       Website
399998    28179.15          0.00           Cash    Completed         Store
399999    17362.95          0.10    Net Banking    Completed    Mobile App

       source_system        last_modified
300000           ERP  2025-12-17 16:00:00
300001           POS  2025-05-15 16:00:00
300002           ERP  2025-11-24 12:00:00
300003     Ecommerce  2025-12-03 12:00:00
300004           POS  2025-02-23 21:00:00
...              ...                  ...
399995           POS  2025-04-12 07:00:00
399996           POS  2025-04-09 22:00:00
399997           POS  2025-12-13 22:00:00
399998           ERP  2025-12-17 20:00:00
399999           POS  2025-12-07 00:00:00

[100000 rows x 12 columns]
CHUNK 5
        transaction_id  order_date  customer_id  product_id  quantity  \
400000          400001  2025-10-04      17470.0         116       3.0
400001          400002  2025-01-14      29182.0         277       4.0
400002          400003  2025-11-04      10278.0          85       7.0
400003          400004  2025-07-18      29706.0          80       4.0
400004          400005  2025-04-06       2545.0         679       1.0
...                ...         ...          ...         ...       ...
499995          499996  2025-09-17      29442.0         575       7.0
499996          499997  2025-01-07      10734.0         928       1.0
499997          499998  2025-06-11      46849.0         165       3.0
499998          499999  2025-12-15      22487.0         187       5.0
499999          500000  2025-11-23      31853.0         169       4.0

        unit_price  discount_pct payment_method order_status sales_channel  \
400000    27662.57          0.00     Debit Card    Cancelled         Store
400001     5445.60          0.00           Cash    Completed       Website
400002    44612.19          0.00     Debit Card      Pending       Website
400003    33868.06          0.20    Credit Card    Completed         Store
400004    22396.22          0.15    Net Banking    Cancelled         Store
...            ...           ...            ...          ...           ...
499995    46985.35          0.00     Debit Card     Returned         Store
499996    23098.75          0.05     Debit Card    Cancelled         Store
499997    12050.28          0.10    Credit Card    Completed    Mobile App
499998    31725.85          0.00            UPI    Completed       Website
499999     8055.48          0.00    Net Banking    Completed       Website

       source_system        last_modified
400000           ERP  2025-10-05 22:00:00
400001           POS  2025-01-16 13:00:00
400002           POS  2025-11-05 02:00:00
400003           POS  2025-07-18 00:00:00
400004           ERP  2025-04-06 18:00:00
...              ...                  ...
499995           POS  2025-09-19 12:00:00
499996     Ecommerce  2025-01-09 03:00:00
499997           POS  2025-06-11 15:00:00
499998           ERP  2025-12-17 06:00:00
499999     Ecommerce  2025-11-25 06:00:00

[100000 rows x 12 columns]
CHUNK 6
        transaction_id  order_date  customer_id  product_id  quantity  \
500000          500001  2025-08-25       2501.0         453       4.0
500001          500002  2025-09-25       6592.0         918       1.0
500002          500003  2025-06-01      19081.0         789       1.0
500003          500004  2025-07-05      27890.0         263       4.0
500004          500005  2025-06-07      37814.0         837       6.0
...                ...         ...          ...         ...       ...
599995          599996  2025-01-30      22238.0         322       3.0
599996          599997  2025-05-19      47598.0         559       7.0
599997          599998  2025-01-21       5729.0         570       3.0
599998          599999  2025-03-07      33681.0         783       6.0
599999          600000  2025-12-13       6642.0         909       6.0

        unit_price  discount_pct payment_method order_status sales_channel  \
500000    36042.42          0.00    Net Banking    Completed       Website
500001     5951.94          0.00            UPI    Cancelled    Mobile App
500002    16962.03          0.10           Cash      Pending    Mobile App
500003    13846.91          0.00    Credit Card      Pending         Store
500004    43600.56          0.10     Debit Card    Cancelled    Mobile App
...            ...           ...            ...          ...           ...
599995    27821.57          0.15    Net Banking     Returned    Mobile App
599996     3293.60          0.05    Credit Card    Completed         Store
599997    38430.75          0.00            UPI    Completed         Store
599998    46081.21          0.05    Net Banking    Completed         Store
599999    28087.76          0.00            UPI    Completed    Mobile App

       source_system        last_modified
500000           ERP  2025-08-25 11:00:00
500001           ERP  2025-09-27 13:00:00
500002           POS  2025-06-03 06:00:00
500003           POS  2025-07-06 17:00:00
500004           ERP  2025-06-07 21:00:00
...              ...                  ...
599995           POS  2025-02-01 23:00:00
599996     Ecommerce  2025-05-19 15:00:00
599997     Ecommerce  2025-01-23 16:00:00
599998           POS  2025-03-08 03:00:00
599999     Ecommerce  2025-12-13 20:00:00

[100000 rows x 12 columns]
CHUNK 7
        transaction_id  order_date  customer_id  product_id  quantity  \
600000          600001  2025-10-15      41017.0          94       7.0
600001          600002  2025-06-06      43511.0         869       2.0
600002          600003  2025-01-20      15508.0         401       2.0
600003          600004  2025-11-03      42036.0         931       6.0
600004          600005  2025-12-21      49930.0         990       4.0
...                ...         ...          ...         ...       ...
699995          699996  2025-10-10      21720.0         165       2.0
699996          699997  2025-08-10      38495.0         722       7.0
699997          699998  2025-04-14      34742.0         827       2.0
699998          699999  2025-01-22      20224.0          45       4.0
699999          700000  2025-10-03      24455.0         614       3.0

        unit_price  discount_pct payment_method order_status sales_channel  \
600000    28125.07          0.00            UPI    Cancelled    Mobile App
600001    26418.70          0.10    Credit Card    Completed         Store
600002     5826.32          0.05     Debit Card    Cancelled       Website
600003    26081.61          0.00    Credit Card    Completed       Website
600004    46689.27          0.00            UPI    Completed       Website
...            ...           ...            ...          ...           ...
699995    12050.28          0.00     Debit Card    Completed         Store
699996    10766.04          0.00           Cash      Pending         Store
699997    40932.33          0.00    Credit Card     Returned       Website
699998    30831.82          0.15           Cash    Completed    Mobile App
699999    47178.35          0.00     Debit Card    Completed    Mobile App

       source_system        last_modified
600000           ERP  2025-10-17 03:00:00
600001           ERP  2025-06-07 08:00:00
600002     Ecommerce  2025-01-22 14:00:00
600003           ERP  2025-11-05 05:00:00
600004     Ecommerce  2025-12-22 05:00:00
...              ...                  ...
699995     Ecommerce  2025-10-11 10:00:00
699996           ERP  2025-08-11 11:00:00
699997     Ecommerce  2025-04-14 10:00:00
699998           ERP  2025-01-24 17:00:00
699999     Ecommerce  2025-10-04 23:00:00

[100000 rows x 12 columns]
CHUNK 8
        transaction_id  order_date  customer_id  product_id  quantity  \
700000          700001  2025-06-30      39236.0          39       1.0
700001          700002  2025-02-16      44842.0         385       1.0
700002          700003  2025-02-07      18487.0         307       4.0
700003          700004  2025-12-23      20366.0         889       7.0
700004          700005  2025-05-06      39301.0         677       2.0
...                ...         ...          ...         ...       ...
799995          799996  2025-03-15      13187.0         153       6.0
799996          799997  2025-11-04      34031.0          25       5.0
799997          799998  2025-09-13      45982.0         500       2.0
799998          799999  2025-11-04      25255.0         203       4.0
799999          800000  2025-12-26      36986.0         138       5.0

        unit_price  discount_pct payment_method order_status sales_channel  \
700000    37890.84          0.05            NaN    Completed    Mobile App
700001    44821.49          0.00           Cash     Returned       Website
700002    48139.94          0.20           Cash     Returned         Store
700003      393.17          0.00    Net Banking    Cancelled       Website
700004    47807.94          0.10            UPI    Completed    Mobile App
...            ...           ...            ...          ...           ...
799995    48560.18          0.10           Cash    Completed         Store
799996    19669.61          0.05            UPI     Returned    Mobile App
799997    17058.68          0.15           Cash    Completed       Website
799998    47872.42          0.00     Debit Card    Cancelled         Store
799999    15696.29          0.00    Net Banking    Completed         Store

       source_system        last_modified
700000     Ecommerce  2025-07-01 20:00:00
700001     Ecommerce  2025-02-16 19:00:00
700002           POS  2025-02-09 23:00:00
700003           POS  2025-12-24 16:00:00
700004           ERP  2025-05-08 11:00:00
...              ...                  ...
799995           POS  2025-03-16 11:00:00
799996           POS  2025-11-06 09:00:00
799997     Ecommerce  2025-09-13 05:00:00
799998           POS  2025-11-05 03:00:00
799999           POS  2025-12-27 12:00:00

[100000 rows x 12 columns]
CHUNK 9
        transaction_id  order_date  customer_id  product_id  quantity  \
800000          800001  2025-04-14      44159.0         623       4.0
800001          800002  2025-03-12      18515.0         617       4.0
800002          800003  2025-04-28      44113.0         864       5.0
800003          800004  2025-08-30      15629.0         106       4.0
800004          800005  2025-06-24      26731.0         787       6.0
...                ...         ...          ...         ...       ...
899995          899996  2025-05-07      30779.0         134       6.0
899996          899997  2025-07-13      26462.0         970       7.0
899997          899998  2025-05-22      35297.0         841       1.0
899998          899999  2025-01-22      39067.0         472       6.0
899999          900000  2025-03-26       5572.0         797       5.0

        unit_price  discount_pct payment_method order_status sales_channel  \
800000    45636.23          0.15           Cash    Completed         Store
800001    36527.26          0.15    Credit Card    Completed    Mobile App
800002     5039.85          0.05           Cash    Completed    Mobile App
800003    30656.82          0.00     Debit Card    Completed       Website
800004     1243.14          0.20           Cash     Returned       Website
...            ...           ...            ...          ...           ...
899995    14285.91          0.10           Cash    Completed    Mobile App
899996    15533.84          0.00    Credit Card    Completed         Store
899997    33462.39          0.00    Credit Card    Completed         Store
899998    40484.52          0.00    Net Banking    Completed       Website

In [16]:
# 9. Find the top 10 customers by transaction count.

df=transactions_cleaned.groupby('customer_id')['transaction_id'].count().sort_values(ascending=False).head(10)
df

customer_id
9999999.0    597
19818.0       43
18438.0       41
33944.0       41
7363.0        40
42110.0       38
18683.0       38
32625.0       38
18416.0       38
2599.0        37
Name: transaction_id, dtype: int64

In [17]:
# 10. Calculate gross, discount, and net amount using vectorized Pandas operations (avoid row-wise `apply` where possible).
transactions_cleaned['gross_amt']=transactions_cleaned['quantity']*transactions_cleaned['unit_price']
transactions_cleaned['disc_amt']=transactions_cleaned['quantity']*transactions_cleaned['discount_pct']
transactions_cleaned['total_amt']=transactions_cleaned['gross_amt']-transactions_cleaned['disc_amt']
transactions_cleaned

,transaction_id,order_date,customer_id,product_id,quantity,unit_price,discount_pct,payment_method,order_status,sales_channel,source_system,last_modified,gross_amt,disc_amt,total_amt
0,1,2025-02-03,4593.0,853,2.0,15213.86,0.00,Debit Card,Returned,Website,Ecommerce,2025-02-05 05:00:00,30427.72,0.00,30427.72
1,2,2025-05-15,21441.0,844,2.0,34802.76,0.00,Credit Card,Completed,Mobile App,ERP,2025-05-16 18:00:00,69605.52,0.00,69605.52
2,3,2025-04-10,32078.0,560,4.0,16944.67,0.00,Cash,Cancelled,Website,ERP,2025-04-12 20:00:00,67778.68,0.00,67778.68
3,4,2025-06-27,16862.0,985,5.0,17010.34,0.10,Debit Card,Completed,Store,ERP,2025-06-27 08:00:00,85051.70,0.50,85051.20
4,5,2025-01-14,16297.0,532,5.0,37642.03,0.15,Net Banking,Cancelled,Store,POS,2025-01-15 09:00:00,188210.15,0.75,188209.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,2025-08-29,35587.0,493,1.0,43648.31,0.00,Cash,Cancelled,Store,ERP,2025-08-31 04:00:00,43648.31,0.00,43648.31
999996,999997,2025-02-11,37772.0,141,2.0,41632.12,0.05,Debit Card,Completed,Store,POS,2025-02-13 16:00:00,83264.24,0.10,83264.14
999997,999998,2025-09-12,32544.0,891,6.0,7390.87,0.15,Net Banking,Returned,Mobile App,ERP,2025-09-13 07:00:00,44345.22,0.90,44344.32
999998,999999,2025-07-01,18873.0,874,1.0,32474.39,0.00,Credit Card,Completed,Store,ERP,2025-07-01 11:00:00,32474.39,0.00,32474.39
999999,1000000,2025-09-26,48937.0,85,3.0,44612.19,0.10,Debit Card,Completed,Store,Ecommerce,2025-09-28 06:00:00,133836.57,0.30,133836.27

In [18]:
'''
### Part B — Bronze layer
    11. Explain why Bronze should preserve source data.
    12. Copy or register the raw CSV as the immutable Bronze input and record file name, load timestamp, and row count in a simple audit table/CSV.
    13. Create a file-level validation report: file exists, schema columns present, and row count.
    14. Identify malformed or invalid records, but do not overwrite the source file.
    15. Create an ingestion audit record for each run.
'''

'\n### Part B — Bronze layer\n    11. Explain why Bronze should preserve source data.\n    12. Copy or register the raw CSV as the immutable Bronze input and record file name, load timestamp, and row count in a simple audit table/CSV.\n    13. Create a file-level validation report: file exists, schema columns present, and row count.\n    14. Identify malformed or invalid records, but do not overwrite the source file.\n    15. Create an ingestion audit record for each run.\n'

In [19]:
# 11. Explain why Bronze should preserve source data.

'''
    Source Data should not be altered . To identify clean as well as malformed data reporting.
'''

'\n    Source Data should not be altered . To identify clean as well as malformed data reporting.\n'

In [20]:
# 12 Read all the files from the bronze csv's and dump metadata of file like filename , whene the file was loaded , no of rows in file and colnames
# 13. Create a file-level validation report: file exists, schema columns present, and row count.


import os,datetime,shutil

files_to_be_removed=["silver","gold","silver_rejected","file_validation_report.csv"]

for file in files_to_be_removed:
    if os.path.exists(file):
    
        if file.endswith(".csv"):
            os.remove(file)
        else:
            shutil.rmtree(file)

path=f"bronze"

list_of_dict=[]

files=os.listdir(path)
for index,file in enumerate(files):
       try:
           if file.endswith(".csv"):
               list_of_dict.append({})
               list_of_dict[-1]["file_name"]=file
               df=pd.read_csv(f'{path}/{file}')
               list_of_dict[-1]["row_count"]=df.shape[0]
               list_of_dict[-1]["load_time"]=datetime.datetime.now().timestamp()
               list_of_dict[-1]["columns"]=",".join(list(df.columns))
       except Exception as e:
           print(e)

df=pd.DataFrame(list_of_dict)
df.to_csv("file_validation_report.csv")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'file_validation_report.csv'

In [ ]:
# 14.Identify malformed and invalid records

transactions.dtypes

In [ ]:
products.dtypes

In [ ]:
customers.dtypes

In [ ]:
# Find invalid Data
invalid_transtion_records=transactions[ transactions['transaction_id'].isnull() |  transactions['customer_id'].isnull()]
invalid_products=products[ products['product_id'].isnull() ]
invalid_customers=customers[ customers['customer_id'].isnull() | customers['customer_name'].isnull()  ]


invalid_transtion_records

In [ ]:
invalid_products

In [ ]:
invalid_customers

In [ ]:
# ************************* SILVER DUMP *************************************************
# 15. Create an ingestion audit record for each run.

transactions=transactions[ ~transactions['transaction_id'].isnull() &  ~transactions['customer_id'].isnull()]
transactions=transactions.drop_duplicates(subset=['transaction_id'],keep='first')
transactions['load_time']=pd.Timestamp.now()

products=products[ ~products['product_id'].isnull() ]
products=products.drop_duplicates(subset=['product_id'],keep='first')
products['load_time']=pd.Timestamp.now()


customers=customers[~ customers['customer_id'].isnull() & ~customers['customer_name'].isnull()  ]
customers=customers.drop_duplicates(subset=['customer_id'],keep='first')
customers['load_time']=pd.Timestamp.now()


os.mkdir("silver")

customers.to_csv("silver/customers.csv",index=False)
products.to_csv("silver/products.csv",index=False)
transactions.to_csv("silver/transactions.csv",index=False)

In [ ]:
### Part C — Silver layer cleaning

'''
16. Standardize column names to lowercase snake_case.
17. Convert `order_date` and `last_modified` to datetime and numeric fields to suitable types.
18. Remove duplicate transactions using `transaction_id` and latest `last_modified`.
19. Validate required fields and create a `reject_reason` for each rejected row.
20. Separate records with missing required values into `silver_rejected.csv`.
21. Reject rows with quantity <= 0.
22. Reject rows where discount_pct is outside 0–1.
23. Find customer IDs missing from the customer master.
24. Find product IDs missing from the product master.
25. Join valid transactions with customer and product master data.
26. Handle unexpected order statuses by flagging them rather than silently changing them.
27. Save cleaned valid data as Parquet (or CSV if Parquet support is not installed).
28. Report counts: source rows, duplicate rows, valid rows, rejected rows, and final Silver rows.
'''

In [ ]:
transactions=pd.read_csv("silver/transactions.csv")
products=pd.read_csv("silver/products.csv")
customers=pd.read_csv("silver/customers.csv")

products

In [ ]:
# 16. Standardize column names to lowercase snake_case.

products.columns=["_".join( col.lower().split(" ") ) for col in products.columns]
customers.columns=["_".join( col.lower().split(" ") ) for col in customers.columns]
transactions.columns=["_".join( col.lower().split(" ") ) for col in transactions.columns]

In [ ]:
# 17. Convert `order_date` and `last_modified` to datetime and numeric fields to suitable types.

transactions['order_date']=pd.to_datetime(transactions['order_date'])
transactions['load_time']=pd.to_datetime(transactions['load_time'])
transactions['last_modified']=pd.to_datetime(transactions['last_modified'])

transactions.head(10)

In [ ]:
transactions.dtypes

In [ ]:
products.dtypes

In [ ]:
products['load_time']=pd.to_datetime(products['load_time'])
products.dtypes

In [ ]:
customers['load_time']=pd.to_datetime(customers['load_time'])
customers.dtypes

In [ ]:
# 18. Remove duplicate transactions using `transaction_id` and latest `last_modified`.
transactions=transactions.sort_values(['transaction_id','last_modified'],ascending=[True,True]).drop_duplicates(subset=['transaction_id','last_modified'])
transactions

In [ ]:
# 21. Reject rows with quantity <= 0.
transactions.loc[ transactions['quantity']<0 , 'reject_reason' ]="Quantity is lt 0"
# 22. Reject rows where discount_pct is outside 0–1.
transactions.loc[ ~ transactions['discount_pct'].between(0,1) , 'reject_reason' ]="Invalid discount_pct"

os.mkdir("silver_rejected")

bad_records=transactions[~ transactions['reject_reason'].isnull()]
bad_records.to_csv("silver_rejected/bad_transactions.csv")
transactions.drop("reject_reason",axis=1,inplace=True)

In [ ]:
"""
23. Find customer IDs missing from the customer master.
24. Find product IDs missing from the product master.
25. Join valid transactions with customer and product master data.
26. Handle unexpected order statuses by flagging them rather than silently changing them.
27. Save cleaned valid data as Parquet (or CSV if Parquet support is not installed).
28. Report counts: source rows, duplicate rows, valid rows, rejected rows, and final Silver rows.
"""

In [ ]:
# 23. Find customer IDs missing from the customer master.
customers[customers['customer_id'].isnull()]

In [ ]:
#24. Find product IDs missing from the product master.
products[products['product_id'].isnull()]
transactions['gross_amt']=transactions['quantity']*transactions['unit_price']
transactions['disc_amt']=transactions['quantity']*transactions['discount_pct']
transactions['total_amt']=transactions['gross_amt']-transactions['disc_amt']

In [ ]:
merged_df=customers.merge(transactions,how="outer",on='customer_id').merge(products,on='product_id',how='outer')
merged_df

In [ ]:
merged_df['order_status'].value_counts()

In [ ]:
# DUMPING MEREGED VALID DF TO SILVER

merged_df.to_csv("silver/merged.csv",index=False)

In [ ]:
'''
### Part D — SQL practice
Use SQLite, PostgreSQL, SQL Server, or another SQL engine. Load the Silver transactions and dimensions into tables.

29. Write a query to return the 10 highest-value completed transactions.
30. Find total completed revenue by month.
31. Find revenue by product category.
32. Find the top 10 customers by completed revenue.
33. Find order count and revenue by city and state.
34. Calculate completed, cancelled, returned, and pending order counts.
35. Find customers who have never placed a completed order.
36. Find products with no transactions.
37. Use `ROW_NUMBER()` to find the latest transaction per customer.
38. Use `DENSE_RANK()` to rank product categories by revenue.
39. Use a CTE to calculate monthly revenue and month-over-month change.
40. Find duplicate `transaction_id` values using `GROUP BY` and `HAVING`.
41. Find customers whose completed revenue is above the average customer revenue.
42. Calculate each category's percentage contribution to total completed revenue.
43. Find the running total of daily completed revenue using a window function.
'''

In [ ]:

merged=pd.read_csv("silver/merged.csv")
merged.head(10)

In [ ]:
# LOAD MERGED DF TO TABLE
from sqlalchemy import create_engine

connection=create_engine("mysql+pymysql://root:root@localhost:3306/offline_16")
print("Hello World")

In [ ]:
merged.dtypes

*********************************** SQL PART *************************************************-

In [ ]:

# UNCOMMENT TO PERFORM INSERT
/*
rows=merged.to_sql(name='dim_orders',con=connection,if_exists='replace',index=False)
rows
*/

# 29. Write a query to return the 10 highest-value completed transactions.
pd.read_sql_query("select * from dim_orders order by total_amt desc limit 10",con=connection)

pd.read_sql_query("select month(cast(order_date as datetime)) as month,sum(total_amt) from dim_orders group by month(cast(order_date as datetime));",con=connection)

pd.read_sql_query("select category,sum(total_amt) from dim_orders group by category;",con=connection)

pd.read_sql_query("select customer_name,sum(total_amt) as lifetime_spend from dim_orders group by customer_name order by lifetime_spend desc limit 10;",con=connection)

pd.read_sql_query("select state,city,sum(total_amt) from dim_orders group by state,city;",con=connection)

# 34. Calculate completed, cancelled, returned, and pending order counts.
pd.read_sql_query("select order_status,count(transaction_id) from dim_orders group by order_status;",con=connection)

#35. Find customers who have never placed a completed order.

pd.read_sql_query("""with cte as (
                    	select distinct customer_id from dim_orders where order_status='completed'
                    )
                    select distinct customer_id from dim_orders where customer_id not in(select * from cte);""",
                 con=connection)

# 36. Find products with no transactions.

pd.read_sql_query("""
                with cte as(
                    select distinct product_id from dim_orders where transaction_id is not null 
                )
                select distinct product_id from dim_orders where product_id not in ( select * from cte)
                """,
                 con=connection)

# 37.First Order by Customer ID -- CRASH
'''
pd.read_sql_query(
    """
    with cte as(
    	select * , row_number() over(partition by customer_id order by cast(order_date as datetime) desc ) rn from dim_orders
    )
    select * from cte where rn=1;
    """,
    con=connection
)
'''

# 38. Use `DENSE_RANK()` to rank product categories by revenue.

pd.read_sql_query(
    """
        with cte as(
            select category,sum(total_amt) as total_cat_sale from dim_orders group by category
        )
        select * , dense_rank() over(order by total_cat_sale desc) as rn from cte
    """,
    con=connection
)

# 39. Use a CTE to calculate monthly revenue and month-over-month change.

pd.read_sql_query(
    """
        with cte as(
            select MONTH(cast(order_date as datetime)) as month,  
                   YEAR(cast(order_date as datetime)) as year , 
                   sum(total_amt) as total_sale from dim_orders 
            group by MONTH(cast(order_date as datetime)),YEAR(cast(order_date as datetime))
            order by year asc , month asc
        ),
        cte2 as(
            select *, lag(total_sale) over(order by year asc, month asc) as last_sale from cte
        )
        select *,total_sale-last_sale from cte2 
    """,
    con=connection
)

# 40. Find duplicate `transaction_id` values using `GROUP BY` and `HAVING`.

pd.read_sql_query('''
    select transaction_id,count(*) from dim_orders group by transaction_id having count(*)>=1
''',con=connection)

# 41. Find customers whose completed revenue is above the average customer revenue.

pd.read_sql_query('''
    with cte as(
        select customer_id, sum(total_amt) as lifetime_spend from dim_orders group by customer_id
    )
    select distinct customer_id,lifetime_spend  from cte where lifetime_spend> (
        select avg(total_amt) from dim_orders
    )
    
''',con=connection)

# 42. Calculate each category's percentage contribution to total completed revenue.

pd.read_sql_query('''
    with cte as(
        select customer_id, sum(total_amt) as lifetime_spend from dim_orders group by customer_id
    ),
    cte2 as(
        select sum(total_amt) as total_sale from dim_orders
    )
    select c1.*,(c1.lifetime_spend/c2.total_sale )*100 as emp_contrbution from cte c1, cte2 c2
''',con=connection)

# 43. Find the running total of daily completed revenue using a window function.

pd.read_sql_query(
    """
        select *, sum(total_amt) over(order by year(cast(order_date as datetime)) asc,month(cast(order_date as datetime)) asc , date(cast(order_date as datetime)) asc  ) as running_sum  from dim_orders
    """,
    con=connection
)

************************************************** GOLD LAYER *************************************************************

### Part E — Gold layer business metrics

44. Build `gold_monthly_sales`: month, order_count, gross_revenue, discount_amount, net_revenue.
45. Build `gold_category_sales`: category, order_count, net_revenue, revenue_rank.
46. Build `gold_customer_360`: customer, city, segment, completed_order_count, lifetime_revenue, last_order_date.
47. Build `gold_order_status_summary`: status, order_count, percentage_of_orders.
48. Build `gold_daily_sales`: order_date, completed_orders, net_revenue, running_revenue.
49. Explain which Gold tables are suitable for dashboards and why.
50. Reconcile Silver totals against Gold aggregates and explain any differences.

In [ ]:
os.mkdir("gold")
print("CREATING GOLD DIRECTORY")

In [ ]:
# 44. Build `gold_monthly_sales`: month, order_count, gross_revenue, discount_amount, net_revenue.
merged['month']=pd.to_datetime(merged['order_date']).dt.month
merged

In [ ]:
df=merged.groupby('month').agg(
    monthly_transactions=("transaction_id","count"),
    total_gross_revenue=("gross_amt","sum"),
    total_disc_amount=("disc_amt","sum"),
    total_net_revenue=("total_amt","sum")
)
df.to_csv("gold/gold_monthly_sales.csv",index=False)

In [ ]:
# 45. Build `gold_category_sales`: category, order_count, net_revenue, revenue_rank.
df=merged.groupby('category').agg(
    monthly_transactions=("transaction_id","count"),
    total_gross_revenue=("gross_amt","sum"),
    total_disc_amount=("disc_amt","sum"),
    total_net_revenue=("total_amt","sum")
)
df['net_rev_rank']=df['total_net_revenue'].rank(method="dense",ascending=False)
#df.to_csv("gold/gold_monthly_sales.csv",index=False)
df

In [ ]:
#46. Build `gold_customer_360`: customer, city, segment, completed_order_count, lifetime_revenue, last_order_date.

df=merged[ merged['order_status'] == "Completed"  ].groupby(['customer_name','city','customer_segment']).agg(
    completed_order_count = ("transaction_id","count")
)

df= df.merge( merged.groupby('customer_name')['order_date'].max() , on ="customer_name",how="left")
df=df.merge( merged.groupby('customer_name')['total_amt'].sum() , on ="customer_name",how="left" )
df.rename({"order_date":"last_order_date","total_amt":"lifetime_spend"},axis=1,inplace=True)
df.to_csv("gold/gold_customer_360.csv")

In [ ]:
# 47. Build `gold_order_status_summary`: status, order_count, percentage_of_orders.
df=merged.groupby('order_status').agg(
    order_count=("transaction_id","count"),
)
order_count= int (merged['transaction_id'].count())
df['order_percentage']=df['order_count']/order_count *100
df.to_csv("gold/gold_order_status_summary.csv")

In [ ]:
merged.dtypes

In [ ]:
# 48. Build `gold_daily_sales`: order_date, completed_orders, net_revenue, running_revenue.

df=merged[merged['order_status']=="Completed"].groupby(["order_date"]).agg(
    completed_order_count=("transaction_id","count")
)
df=df.merge( merged.groupby(["order_date"]).agg( net_revenue=("total_amt","sum")  ) , on=["order_date"], how="outer" )
df.sort_values("order_date",ascending=True,inplace=True)
df['running_net_revenue']=df['net_revenue'].cumsum()
df['completed_order_count']=df['completed_order_count'].fillna(0)
df.to_csv("gold/gold_daily_sales.csv")
df